# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
# Copyright (c) 2026 Phidipus Agents (see NOTICE)
"""
memory_integrity/memory_guard.py — Phidipus v1.0
HMAC-SHA256 integrity layer — single entry point for all episode read/write.

Architecture contract (R-16 / R-20):
  "All writes: HMAC-SHA256 sign via memory_guard.py.  All reads: verify
   signature, reject invalid.  Startup integrity scan of all core modules
   against SHA256_MANIFEST before the agent loop starts."

MemoryGuard is the ONLY module permitted to read or write episode files
to disk.  No other module in the memory subsystem may perform direct file
I/O.  All callers (EpisodicMemory, VectorMemory) go through this class.

On-disk format (per episode file)
----------------------------------
Each episode is stored as a single JSON file at::

    <episodes_root>/<namespace>/<episode_id>.ep.json

The file contains a signed envelope::

    {
      "data":    { ...episode dict... },
      "hmac":    "<64-char hex HMAC-SHA256>",
      "version": 1
    }

HMAC coverage
-------------
The HMAC-SHA256 is computed over the UTF-8 bytes of the canonical JSON
serialisation of the ``data`` dict (with ``sort_keys=True``).  This
ensures the HMAC is deterministic regardless of key insertion order.

Key management
--------------
The 32-byte HMAC key is loaded from ``cfg.memory.hmac_key_file`` at
construction time.  The key file must be generated by the installer
(``generate_installation_keys()``) with mode 0600 before the daemon
starts.  MemoryGuard validates key length at init and fails fast if the
key is absent or wrong length.

Startup integrity scan (R-20 component)
----------------------------------------
``startup_integrity_scan()`` verifies HMAC signatures on all episodes in
the primary namespace at daemon start.  Episodes that fail verification
are quarantined (renamed to ``<id>.ep.json.quarantine``) and excluded
from normal reads.  The scan result is returned as a dataclass so the
agent loop can decide whether to abort or proceed with warnings.

Namespace routing
-----------------
MemoryGuard accepts an optional ``segment_router`` parameter (a
SegmentRouter instance).  When not provided, an internal
``_DefaultPathResolver`` is used, which provides the same directory
layout without the cross-namespace access control of SegmentRouter.
Production use should always inject a SegmentRouter.

    # Production:
    router = SegmentRouter(cfg)
    guard  = MemoryGuard(cfg, segment_router=router)

    # Phase 1 compat / testing (no access control):
    guard  = MemoryGuard(cfg)

The ``namespace_dir()`` public method is the authorised way for
EpisodicMemory to resolve the index file path, replacing the previous
fragile access to ``guard._router.namespace_dir()``.

Process: orchestrator (L1)

Security invariants enforced here:
  R-16  Every episode written to disk is HMAC-SHA256 signed.
        Every episode read from disk has its HMAC verified before the
        data is returned.  Episodes with invalid or absent HMACs raise
        IntegrityError and are never returned to callers.
  R-20  startup_integrity_scan() verifies all episodes in the primary
        namespace on daemon startup.  Corrupt episodes are quarantined
        and the scan result is reported to the agent loop.
  R-07  No exec(), eval(), exec_module() calls anywhere in this module.
  R-02  No subprocess or OS shell calls.

Used by:
  memory/episodic_memory.py  — write_episode(), read_episode(),
                               delete_episode(), list_episodes(),
                               namespace_dir()

Dependencies:
  memory_integrity/segment_router.py — SegmentRouter (path routing +
                                        namespace access control)
  utils/atomic_file.py               — atomic_write_bytes(), safe_read_bytes()
  utils/hash_utils.py                — hmac_sign(), hmac_verify(), sha256_hex()
  utils/json_utils.py                — dumps(), loads(), dumps_bytes(),
                                       load_bytes(), JsonDecodeError
  utils/file_ops.py                  — safe_join(), ensure_dir(),
                                       is_safe_filename()
  utils/logger.py                    — get_logger()
  config/config_loader.py            — PhidipusConfig
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Union

from config.config_loader import PhidipusConfig
from memory_integrity.segment_router import (
    VALID_NAMESPACES,
    NamespaceAccessError,
    NamespaceError,
    SegmentRouter,
)
from utils.atomic_file import atomic_write_bytes, safe_read_bytes
from utils.file_ops import ensure_dir, is_safe_filename, safe_join
from utils.hash_utils import hmac_sign, hmac_verify, sha256_hex
from utils.json_utils import (
    JsonDecodeError,
    dumps,
    dumps_bytes,
    load_bytes,
    loads,
)
from utils.logger import get_logger

_log = get_logger(__name__, process="orchestrator")

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

#: On-disk envelope schema version — increment if format changes.
_ENVELOPE_VERSION: int = 1

#: Episode file extension — must match segment_router._EPISODE_EXT.
_EPISODE_EXT: str = ".ep.json"

#: Suffix appended to quarantined episode files during startup scan.
_QUARANTINE_SUFFIX: str = ".quarantine"

#: Expected HMAC key length in bytes (256-bit key).
_HMAC_KEY_LENGTH: int = 32

#: Default subdirectory under data_dir for episodes (used by _DefaultPathResolver).
_EPISODES_SUBDIR: str = "episodes"

#: Namespace directory permissions (owner read/write/execute only).
_NS_DIR_MODE: int = 0o700

#: Episode file permissions (owner read/write only).
_EP_FILE_MODE: int = 0o600


# ---------------------------------------------------------------------------
# Exceptions
# ---------------------------------------------------------------------------

class IntegrityError(RuntimeError):
    """
    Raised when an episode's HMAC-SHA256 signature fails verification (R-16).

    A caller that receives this exception MUST NOT use the episode data.
    The episode file should be quarantined or deleted.

    Attributes:
        episode_id: The episode identifier that failed verification.
        reason:     Short machine-readable reason code.
    """

    def __init__(
        self,
        message:    str,
        *,
        episode_id: str = "",
        reason:     str = "HMAC_INVALID",
    ) -> None:
        super().__init__(message)
        self.episode_id = episode_id
        self.reason     = reason

    def __str__(self) -> str:
        parts = [f"[{self.reason}]"]
        if self.episode_id:
            parts.append(f"id={self.episode_id!r}")
        return " ".join(parts) + f" {super().__str__()}"


class EpisodeNotFoundError(FileNotFoundError):
    """
    Raised when an episode file does not exist on disk.

    Attributes:
        episode_id: The missing episode identifier.
        namespace:  The namespace that was searched.
        reason:     Always "EPISODE_NOT_FOUND".
    """

    def __init__(
        self,
        message:    str,
        *,
        episode_id: str = "",
        namespace:  str = "",
        reason:     str = "EPISODE_NOT_FOUND",
    ) -> None:
        super().__init__(message)
        self.episode_id = episode_id
        self.namespace  = namespace
        self.reason     = reason

    def __str__(self) -> str:
        parts = [f"[{self.reason}]"]
        if self.episode_id:
            parts.append(f"id={self.episode_id!r}")
        if self.namespace:
            parts.append(f"ns={self.namespace!r}")
        return " ".join(parts) + f" {super().__str__()}"


class EpisodeValidationError(ValueError):
    """
    Raised when an episode dict fails structural validation before write.

    Attributes:
        field:  Dot-path to the offending field (e.g. ``"id"``).
        reason: Short machine-readable reason code.
    """

    def __init__(
        self,
        message: str,
        *,
        field:  str = "",
        reason: str = "VALIDATION_ERROR",
    ) -> None:
        super().__init__(message)
        self.field  = field
        self.reason = reason

    def __str__(self) -> str:
        parts = [f"[{self.reason}]"]
        if self.field:
            parts.append(f"field={self.field!r}")
        return " ".join(parts) + f" {super().__str__()}"


class MemoryGuardError(RuntimeError):
    """
    Raised on MemoryGuard operational errors (key loading, I/O failures).

    Attributes:
        reason: Short machine-readable reason code.
    """

    def __init__(self, message: str, *, reason: str = "GUARD_ERROR") -> None:
        super().__init__(message)
        self.reason = reason

    def __str__(self) -> str:
        return f"[{self.reason}] {super().__str__()}"


# ---------------------------------------------------------------------------
# Startup scan result
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class IntegrityScanResult:
    """
    Immutable summary of the startup integrity scan (R-20).

    Attributes:
        namespace:      The namespace that was scanned.
        total:          Total number of episode files found.
        verified:       Episodes that passed HMAC verification.
        quarantined:    Episodes that failed and were quarantined.
        skipped:        Episodes skipped due to unreadable files.
        quarantine_ids: IDs of episodes that were quarantined.
    """

    namespace:      str
    total:          int
    verified:       int
    quarantined:    int
    skipped:        int
    quarantine_ids: tuple[str, ...] = field(default_factory=tuple)

    @property
    def all_ok(self) -> bool:
        """True iff no episodes were quarantined or skipped."""
        return self.quarantined == 0 and self.skipped == 0


# ---------------------------------------------------------------------------
# Internal fallback path resolver (no access control)
# ---------------------------------------------------------------------------

class _DefaultPathResolver:
    """
    Minimal path resolver used when no SegmentRouter is injected.

    Provides the same directory layout as SegmentRouter but does NOT
    enforce cross-namespace read access control.  For production use,
    always inject a SegmentRouter.
    """

    def __init__(self, data_dir: Path) -> None:
        self._episodes_root = data_dir / _EPISODES_SUBDIR
        for ns in sorted(VALID_NAMESPACES):
            ensure_dir(self._episodes_root / ns, mode=_NS_DIR_MODE)

    def resolve_path(self, namespace: str, episode_id: str) -> Path:
        if namespace not in VALID_NAMESPACES:
            raise NamespaceError(
                f"Unknown namespace {namespace!r}.",
                namespace=namespace,
            )
        ns_dir = ensure_dir(self._episodes_root / namespace, mode=_NS_DIR_MODE)
        return safe_join(ns_dir, episode_id + _EPISODE_EXT)

    def namespace_dir(self, namespace: str) -> Path:
        if namespace not in VALID_NAMESPACES:
            raise NamespaceError(
                f"Unknown namespace {namespace!r}.",
                namespace=namespace,
            )
        return ensure_dir(self._episodes_root / namespace, mode=_NS_DIR_MODE)


# ---------------------------------------------------------------------------
# MemoryGuard
# ---------------------------------------------------------------------------

class MemoryGuard:
    """
    HMAC-SHA256 integrity layer — sole gatekeeper for episode persistence.

    All episode reads and writes in the Phidipus memory subsystem must go
    through this class.  No other module is permitted to touch episode
    files on disk directly.

    Usage::

        # Production (with namespace access control):
        router = SegmentRouter(cfg)
        guard  = MemoryGuard(cfg, segment_router=router)

        # Write a signed episode:
        dest = guard.write_episode(
            {"id": "ep-001", "task": "open browser", "outcome": "success"},
            namespace="primary",
        )

        # Read and verify:
        episode = guard.read_episode("ep-001", namespace="primary")

        # Startup scan (R-20):
        result = guard.startup_integrity_scan(namespace="primary")
        if not result.all_ok:
            logger.error("Integrity scan found corrupt episodes", ...)

    Args:
        cfg:            Validated PhidipusConfig.
        segment_router: Optional SegmentRouter for namespace access control.
                        If None, a _DefaultPathResolver is used (no
                        cross-namespace access enforcement).
    """

    def __init__(
        self,
        cfg:            PhidipusConfig,
        segment_router: SegmentRouter | None = None,
    ) -> None:
        # ── HMAC key ────────────────────────────────────────────────────
        hmac_key_path = Path(cfg.memory.hmac_key_file)
        if not hmac_key_path.exists():
            raise MemoryGuardError(
                f"HMAC key file not found: {hmac_key_path}. "
                "Run the installer to generate keys before starting.",
                reason="KEY_NOT_FOUND",
            )
        self._hmac_key: bytes = hmac_key_path.read_bytes()
        if len(self._hmac_key) != _HMAC_KEY_LENGTH:
            raise MemoryGuardError(
                f"HMAC key at {hmac_key_path} is {len(self._hmac_key)} bytes; "
                f"expected exactly {_HMAC_KEY_LENGTH} bytes. "
                "The key file may be corrupt — re-run the installer.",
                reason="KEY_INVALID",
            )

        # ── Path router ──────────────────────────────────────────────────
        if segment_router is not None:
            self._router: SegmentRouter | _DefaultPathResolver = segment_router
        else:
            self._router = _DefaultPathResolver(Path(cfg.paths.data_dir))
            _log.warning(
                "MemoryGuard: no SegmentRouter injected — "
                "cross-namespace access control is DISABLED. "
                "Use SegmentRouter in production.",
            )

        _log.info(
            "MemoryGuard initialised",
            extra={
                "hmac_key_path":    str(hmac_key_path),
                "segment_router":   segment_router is not None,
                "default_namespace": cfg.memory.episode_namespace,
            },
        )

    # ------------------------------------------------------------------
    # Public protocol: namespace_dir()
    # ------------------------------------------------------------------

    def namespace_dir(self, namespace: str) -> Path:
        """
        Return the resolved directory Path for *namespace*.

        This is the authorised replacement for accessing ``guard._router``
        directly (which EpisodicMemory previously used to resolve its
        index file path).  Callers should use this method instead of
        touching the internal ``_router`` attribute.

        Args:
            namespace: One of "primary", "guest", "untrusted".

        Returns:
            Absolute Path to the namespace directory (created if needed).

        Raises:
            NamespaceError: if *namespace* is not valid.
        """
        return self._router.namespace_dir(namespace)

    # ------------------------------------------------------------------
    # Public write / read / delete / list
    # ------------------------------------------------------------------

    def write_episode(
        self,
        episode:   dict[str, Any],
        namespace: str = "primary",
    ) -> Path:
        """
        Validate, sign, and write *episode* to disk (R-16).

        Signing process:
          1. Validate episode has a non-empty ``"id"`` field.
          2. Validate ``episode["id"]`` is a safe filename component.
          3. Serialise ``episode`` with ``sort_keys=True`` for deterministic HMAC.
          4. Compute HMAC-SHA256 over the serialised bytes.
          5. Wrap in a signed envelope: ``{"data": ..., "hmac": ..., "version": 1}``.
          6. Write envelope atomically with mode 0o600.

        Args:
            episode:   Episode dict.  Must contain a non-empty ``"id"`` key.
                       All values must be JSON-serialisable.
            namespace: Target namespace ("primary", "guest", "untrusted").

        Returns:
            Path to the written episode file.

        Raises:
            EpisodeValidationError: if episode structure is invalid.
            NamespaceError:         if namespace is not valid.
            MemoryGuardError:       on I/O failure.
        """
        # ── Validate episode structure ───────────────────────────────────
        if not isinstance(episode, dict):
            raise EpisodeValidationError(
                f"Episode must be a dict, got {type(episode).__name__!r}.",
                field="<root>",
                reason="INVALID_TYPE",
            )
        episode_id: str = episode.get("id", "")  # type: ignore[assignment]
        if not isinstance(episode_id, str) or not episode_id:
            raise EpisodeValidationError(
                "Episode must have a non-empty string 'id' field.",
                field="id",
                reason="MISSING_ID",
            )
        # Validate the ID is safe to use as a filename component.
        # is_safe_filename checks for path traversal characters.
        if not is_safe_filename(episode_id):
            raise EpisodeValidationError(
                f"Episode id {episode_id!r} contains unsafe characters. "
                "Only alphanumerics, underscores, hyphens, and dots are allowed.",
                field="id",
                reason="UNSAFE_ID",
            )

        # ── Build HMAC ───────────────────────────────────────────────────
        try:
            data_bytes: bytes = dumps(episode, sort_keys=True).encode("utf-8")
        except (ValueError, TypeError) as exc:
            raise EpisodeValidationError(
                f"Episode is not JSON-serialisable: {exc}",
                field="<root>",
                reason="NOT_SERIALISABLE",
            ) from exc

        mac: bytes    = hmac_sign(self._hmac_key, data_bytes)
        mac_hex: str  = mac.hex()

        # ── Build envelope ───────────────────────────────────────────────
        envelope: dict[str, Any] = {
            "version": _ENVELOPE_VERSION,
            "data":    episode,
            "hmac":    mac_hex,
        }

        # ── Resolve path and write ───────────────────────────────────────
        dest: Path = self._router.resolve_path(namespace, episode_id)

        try:
            envelope_bytes = dumps(envelope, sort_keys=True).encode("utf-8")
            atomic_write_bytes(dest, envelope_bytes, mode=_EP_FILE_MODE)
        except Exception as exc:
            raise MemoryGuardError(
                f"Failed to write episode {episode_id!r} to {dest}: {exc}",
                reason="WRITE_FAILED",
            ) from exc

        _log.debug(
            "R-16: episode written and signed",
            extra={
                "episode_id": episode_id,
                "namespace":  namespace,
                "dest":       str(dest),
            },
        )
        return dest

    def read_episode(
        self,
        episode_id: str,
        namespace:  str = "primary",
        *,
        caller_ns:  str = "",
    ) -> dict[str, Any]:
        """
        Read and HMAC-verify an episode from disk (R-16).

        Verification process:
          1. Enforce namespace read isolation if caller_ns is provided and
             the router is a SegmentRouter (Bug #14 fix).
          2. Resolve the episode file path via the router.
          3. Read the raw bytes from disk.
          4. Parse the JSON envelope.
          5. Re-serialise ``envelope["data"]`` with ``sort_keys=True``.
          6. Verify HMAC-SHA256 against the stored ``envelope["hmac"]``.
          7. Return ``envelope["data"]`` only if HMAC is valid.

        Args:
            episode_id: Episode identifier.
            namespace:  Source namespace.
            caller_ns:  The namespace the calling agent is operating in.
                        When provided and the router is a SegmentRouter,
                        cross-namespace access control is enforced (R-16).
                        When empty (default), no access control check is
                        performed — for backward compatibility with callers
                        that do not yet pass caller_ns.

        Returns:
            Verified episode dict.

        Raises:
            EpisodeNotFoundError:  if the episode file does not exist.
            IntegrityError:        if HMAC verification fails (R-16).
            NamespaceAccessError:  if caller_ns is not permitted to read
                                   namespace (R-16, Bug #14 fix).
            MemoryGuardError:      on I/O or parse error.
        """
        # Bug #14 fix: enforce namespace read isolation when caller_ns is
        # provided and the router supports access control.
        if caller_ns and isinstance(self._router, SegmentRouter):
            self._router.check_read_allowed(caller_ns, namespace)

        path: Path = self._router.resolve_path(namespace, episode_id)

        if not path.exists():
            raise EpisodeNotFoundError(
                f"Episode {episode_id!r} not found in namespace {namespace!r}.",
                episode_id=episode_id,
                namespace=namespace,
            )

        # ── Read and parse ───────────────────────────────────────────────
        try:
            raw: bytes = path.read_bytes()
            envelope   = loads(raw.decode("utf-8"))
        except (OSError, UnicodeDecodeError, JsonDecodeError) as exc:
            raise MemoryGuardError(
                f"Cannot read episode {episode_id!r}: {exc}",
                reason="READ_FAILED",
            ) from exc

        if not isinstance(envelope, dict):
            raise IntegrityError(
                f"Episode {episode_id!r} envelope is not a JSON object.",
                episode_id=episode_id,
                reason="ENVELOPE_CORRUPT",
            )

        # ── Extract fields ───────────────────────────────────────────────
        stored_mac_hex: str = envelope.get("hmac", "")
        data: Any           = envelope.get("data")

        if not stored_mac_hex or not isinstance(stored_mac_hex, str):
            raise IntegrityError(
                f"Episode {episode_id!r} has missing or invalid 'hmac' field (R-16).",
                episode_id=episode_id,
                reason="HMAC_MISSING",
            )
        if not isinstance(data, dict):
            raise IntegrityError(
                f"Episode {episode_id!r} 'data' field is not a dict.",
                episode_id=episode_id,
                reason="DATA_CORRUPT",
            )

        # ── Verify HMAC ──────────────────────────────────────────────────
        # Re-serialise data with sort_keys=True to produce the same bytes
        # that were signed during write_episode().
        try:
            data_bytes: bytes = dumps(data, sort_keys=True).encode("utf-8")
            stored_mac: bytes = bytes.fromhex(stored_mac_hex)
        except (ValueError, TypeError) as exc:
            raise IntegrityError(
                f"Episode {episode_id!r} HMAC field is malformed: {exc}",
                episode_id=episode_id,
                reason="HMAC_MALFORMED",
            ) from exc

        if not hmac_verify(self._hmac_key, data_bytes, stored_mac):
            _log.error(
                "R-16 VIOLATION: episode HMAC verification FAILED",
                extra={
                    "episode_id": episode_id,
                    "namespace":  namespace,
                    "path":       str(path),
                    "reason":     "HMAC_INVALID",
                },
            )
            raise IntegrityError(
                f"Episode {episode_id!r} HMAC is invalid (R-16). "
                "The episode file may have been tampered with or the "
                "HMAC key has changed.",
                episode_id=episode_id,
                reason="HMAC_INVALID",
            )

        _log.debug(
            "R-16: episode verified and returned",
            extra={"episode_id": episode_id, "namespace": namespace},
        )
        return data

    def delete_episode(
        self,
        episode_id: str,
        namespace:  str = "primary",
    ) -> bool:
        """
        Delete an episode file from disk.

        Args:
            episode_id: Episode identifier.
            namespace:  Namespace to delete from.

        Returns:
            True if the file was deleted, False if it did not exist.

        Raises:
            MemoryGuardError: on I/O failure other than FileNotFoundError.
        """
        path: Path = self._router.resolve_path(namespace, episode_id)

        if not path.exists():
            return False

        try:
            path.unlink()
        except OSError as exc:
            raise MemoryGuardError(
                f"Failed to delete episode {episode_id!r}: {exc}",
                reason="DELETE_FAILED",
            ) from exc

        _log.debug(
            "MemoryGuard: episode deleted",
            extra={"episode_id": episode_id, "namespace": namespace},
        )
        return True

    def list_episodes(self, namespace: str = "primary") -> list[str]:
        """
        List all episode IDs present on disk in *namespace*.

        Returns IDs sorted alphabetically (insertion order is maintained
        by EpisodicMemory's index; this method is for count/existence checks).

        Args:
            namespace: Namespace to list.

        Returns:
            Sorted list of episode IDs (without the ``.ep.json`` extension).

        Raises:
            NamespaceError: if namespace is not valid.
        """
        ns_dir: Path = self._router.namespace_dir(namespace)
        ids: list[str] = []
        try:
            for p in ns_dir.iterdir():
                # Bug #12 fix: also reject filenames that contain the
                # quarantine marker anywhere (e.g. "evil.ep.json.quarantine.ep.json"
                # would pass the old suffix-only check).
                if (p.name.endswith(_EPISODE_EXT)
                        and _QUARANTINE_SUFFIX not in p.name):
                    ep_id = p.name[: -len(_EPISODE_EXT)]
                    ids.append(ep_id)
        except OSError as exc:
            _log.warning(
                "MemoryGuard: could not list episodes",
                extra={"namespace": namespace, "error": str(exc)},
            )
        return sorted(ids)

    # ------------------------------------------------------------------
    # Startup integrity scan (R-20)
    # ------------------------------------------------------------------

    def startup_integrity_scan(
        self,
        namespace: str = "primary",
    ) -> IntegrityScanResult:
        """
        Verify HMAC signatures on all episodes in *namespace* (R-20).

        Episodes that fail verification are quarantined by renaming them
        to ``<id>.ep.json.quarantine``.  They are excluded from normal
        reads and from ``list_episodes()``.

        This method is called once at agent-loop startup.  The result is
        returned to the caller (agent_loop.py) which decides whether to
        abort or proceed with a warning if any episodes were quarantined.

        Args:
            namespace: Namespace to scan (default: "primary").

        Returns:
            IntegrityScanResult with counts and quarantined IDs.
        """
        ns_dir: Path = self._router.namespace_dir(namespace)

        total       = 0
        verified    = 0
        quarantined = 0
        skipped     = 0
        quarantine_ids: list[str] = []

        try:
            ep_paths = [
                p for p in ns_dir.iterdir()
                if p.name.endswith(_EPISODE_EXT)
                and not p.name.endswith(_QUARANTINE_SUFFIX)
            ]
        except OSError as exc:
            _log.error(
                "R-20: startup integrity scan could not list namespace directory",
                extra={"namespace": namespace, "error": str(exc)},
            )
            return IntegrityScanResult(
                namespace=namespace,
                total=0, verified=0, quarantined=0, skipped=1,
            )

        for ep_path in ep_paths:
            total += 1
            ep_id = ep_path.name[: -len(_EPISODE_EXT)]

            try:
                self.read_episode(ep_id, namespace=namespace)
                verified += 1
            except IntegrityError as exc:
                # Quarantine the corrupt file
                quarantine_path = ep_path.with_suffix(
                    _EPISODE_EXT + _QUARANTINE_SUFFIX
                )
                try:
                    ep_path.rename(quarantine_path)
                    quarantine_ids.append(ep_id)
                    quarantined += 1
                    _log.error(
                        "R-20: episode quarantined — HMAC invalid",
                        extra={
                            "episode_id":      ep_id,
                            "namespace":       namespace,
                            "quarantine_path": str(quarantine_path),
                            "reason":          exc.reason,
                        },
                    )
                except OSError as rename_exc:
                    skipped += 1
                    _log.error(
                        "R-20: could not quarantine corrupt episode",
                        extra={
                            "episode_id": ep_id,
                            "error":      str(rename_exc),
                        },
                    )
            except (MemoryGuardError, EpisodeNotFoundError) as exc:
                skipped += 1
                _log.warning(
                    "R-20: skipping unreadable episode during scan",
                    extra={"episode_id": ep_id, "error": str(exc)},
                )

        result = IntegrityScanResult(
            namespace=namespace,
            total=total,
            verified=verified,
            quarantined=quarantined,
            skipped=skipped,
            quarantine_ids=tuple(quarantine_ids),
        )

        log_fn = _log.info if result.all_ok else _log.error
        log_fn(
            "R-20: startup integrity scan complete",
            extra={
                "namespace":   namespace,
                "total":       total,
                "verified":    verified,
                "quarantined": quarantined,
                "skipped":     skipped,
                "all_ok":      result.all_ok,
            },
        )
        return result

    def scan_integrity(self, namespace: str = "primary") -> "IntegrityScanAdapter":
        """
        M-16 FIX: Public scan_integrity() wrapper called by agent_loop.startup().
        Runs startup_integrity_scan() and returns a unified adapter
        with fields expected by agent_loop (all_valid, invalid_hmac, etc.).
        Now returns meaningful results — not always-warning.
        """
        result = self.startup_integrity_scan(namespace=namespace)

        class IntegrityScanAdapter:
            def __init__(self, r: "IntegrityScanResult") -> None:
                self.all_valid: bool    = r.all_ok
                self.invalid_hmac: int  = r.quarantined
                self.unreadable: int    = r.skipped
                self.total_files: int   = r.total
                self.invalid_ids: list  = list(r.quarantine_ids)

        return IntegrityScanAdapter(result)
