# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
# Copyright (c) 2026 Phidipus Agents (see NOTICE)
"""
skills/skill_registry.py — Phidipus v1.20 (FIX #2)
Registry for validated, signed skill definitions with quarantine + human-approval gate.

Architecture contract (R-08 / R-09):
  "Register only validated, signed skills.  Add quarantine status for
   new skills.  No loading unsigned skill."

FIX #2 — Human-approval gate:
  ALL LLM-generated and evolved skills now require explicit admin approval
  before they can execute.  The approval gate sits BEFORE the quarantine gate:

      Generated/Evolved skill
          ↓
      Gate 1-2-3 (AST + Docker + Schema)  ← existing
          ↓
      pending_human_approval = True        ← FIX #2: NEW gate
          ↓  (admin approves via Admin Panel or Telegram)
      quarantined = True                   ← existing
          ↓  (runs successfully once)
      quarantined = False  →  active

  Rationale: Gate 1-3 validate syntax and schema, but cannot fully prevent
  a malicious skill that passes all static checks from being executed on the
  host.  A human admin reviewing the skill code before approval is the only
  defence against a Gate-bypass.  The review is a one-time action per skill.

  Manually written / builtin skills are pre-approved (pending=False) because
  they are written by the developer, not generated by an LLM.

SkillRegistry maintains an in-memory catalogue of validated skills and
persists it to skill_versions.json (signed with ed25519 after every
write, R-17).  Only skills that have passed the 3-gate validator and
carry a valid .sig file can be registered (R-09).

Quarantine
----------
Every newly registered skill starts in quarantine.  A quarantined skill
can be discovered and loaded, but the agent loop treats it as untrusted
and may require human confirmation before executing it.  A skill exits
quarantine after executing successfully at least once (promote()).

Process: orchestrator (L1)

Security invariants enforced here:
  R-08  register() rejects skills that lack a ValidationResult.
  R-09  register() verifies the .sig file exists and is valid before
        adding the skill to the registry.
  R-17  Every write to skill_versions.json is immediately followed by
        sign_skill_versions().  On load, the signature is VERIFIED before
        trusting the file contents — tampered registries are rejected.
  FIX-2 approve() is the ONLY path to clear pending_human_approval.
        is_executable() blocks execution until both pending_human_approval=False
        AND quarantined=False (or quarantine override is explicitly requested).

Used by:
  core/agent_loop.py            — register_skill(), get_skill(), is_executable()
  evolution/skill_evolver.py    — register after evolution
  admin/admin_server_v2.py      — approve_skill() endpoint
  telegram/telegram_bot.py      — /skills approve <name>

Dependencies:
  skills/base_skill.py              — BaseSkillDefinition
  skill_validator/schema_gate.py    — ValidationResult
  skill_validator/skill_signer.py   — verify_skill()
  evolution/skill_version_signer.py — sign_skill_versions(),
                                       verify_skill_versions()
  utils/atomic_file.py              — atomic_write_text(), safe_read_bytes()
  utils/json_utils.py               — dumps(), loads()
  utils/logger.py                   — get_logger()
  config/config_loader.py           — PhidipusConfig

FIX (BUG-3 / R-17): _load_versions() previously loaded skill_versions.json
  WITHOUT verifying the ed25519 signature.  An attacker who tampered with
  skill_versions.json could inject unvalidated skills into the registry.
  Fixed by calling verify_skill_versions() before parsing the file.
  If verification fails, the file is rejected and the registry starts empty.
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from config.config_loader import PhidipusConfig
from evolution.skill_version_signer import (
    VersionSignatureError,
    sign_skill_versions,
    verify_skill_versions,
)
from skill_validator.schema_gate import ValidationResult
from skill_validator.skill_signer import SkillSignatureError, verify_skill
from skills.base_skill import BaseSkillDefinition
from utils.atomic_file import atomic_write_bytes, atomic_write_text, safe_read_bytes
from utils.json_utils import JsonDecodeError, dumps, loads
from utils.logger import get_logger

_log = get_logger(__name__, process="orchestrator")

_VERSIONS_FILENAME = "skill_versions.json"


# ---------------------------------------------------------------------------
# Exceptions
# ---------------------------------------------------------------------------

class SkillRegistryError(RuntimeError):
    """
    Raised on SkillRegistry operational errors.

    Attributes:
        skill_name: The skill involved.
        reason:     Short machine-readable reason code.
    """

    def __init__(
        self,
        message: str,
        *,
        skill_name: str = "",
        reason:     str = "REGISTRY_ERROR",
    ) -> None:
        super().__init__(message)
        self.skill_name = skill_name
        self.reason     = reason

    def __str__(self) -> str:
        base  = super().__str__()
        parts = [f"[{self.reason}]"]
        if self.skill_name:
            parts.append(f"skill={self.skill_name!r}")
        return " ".join(parts) + f" {base}"


class SkillNotApprovedError(SkillRegistryError):
    """
    FIX #2: Raised when attempting to execute a skill that has not yet
    received human admin approval.

    The caller must NOT execute the skill.  It should instead:
      1. Notify the admin via Telegram or Admin Panel.
      2. Wait for approve() to be called.
      3. Retry execution after approval.
    """

    def __init__(self, skill_name: str) -> None:
        super().__init__(
            f"Skill {skill_name!r} requires human admin approval before execution. "
            "Use Admin Panel → Skills → Approve, or Telegram /skills approve {skill_name}.",
            skill_name=skill_name,
            reason="SKILL_NOT_APPROVED",
        )


# ---------------------------------------------------------------------------
# SkillRegistry
# ---------------------------------------------------------------------------

class SkillRegistry:
    """
    In-memory + persisted registry of validated skill definitions.

    Usage::

        registry = SkillRegistry(cfg)
        registry.register(validation_result)
        defn = registry.get("open_browser")
        all_skills = registry.list_skills()

        # FIX #2: check before executing
        if not registry.is_executable("open_browser"):
            raise SkillNotApprovedError("open_browser")

    Args:
        cfg: Validated PhidipusConfig.
    """

    def __init__(self, cfg: PhidipusConfig) -> None:
        self._pub_key_path   = Path(cfg.skill_validator.signing_public_key_file)
        self._priv_key_path  = Path(cfg.skill_validator.signing_private_key_file)
        self._versions_path  = Path(cfg.paths.data_dir) / _VERSIONS_FILENAME
        self._skills:        dict[str, BaseSkillDefinition] = {}
        self._load_versions()

        _log.info(
            "SkillRegistry initialised",
            extra={
                "loaded":        len(self._skills),
                "versions_path": str(self._versions_path),
            },
        )

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def register(self, validation: ValidationResult) -> BaseSkillDefinition:
        """
        Register a validated, signed skill (R-08, R-09).

        FIX #2: All LLM-generated skills start with:
          - pending_human_approval = True  (blocks execution until admin approves)
          - quarantined = True             (blocks promotion until 1 success run)

        Verifies the .sig file before registration.

        Args:
            validation: ValidationResult from SchemaGate (all 3 gates passed).

        Returns:
            The registered BaseSkillDefinition.

        Raises:
            SkillRegistryError: if sig verification fails or name conflicts.
        """
        skill_name = validation.skill_name

        # R-09: verify .sig is present and valid
        try:
            verify_skill(validation.skill_path, self._pub_key_path)
        except (SkillSignatureError, FileNotFoundError) as exc:
            _log.error(
                "R-09: SkillRegistry rejected unsigned/invalid skill",
                extra={"skill_name": skill_name, "error": str(exc)},
            )
            raise SkillRegistryError(
                f"Skill {skill_name!r} has invalid or missing .sig — "
                "registration denied (R-09).",
                skill_name=skill_name,
                reason="SIG_INVALID",
            ) from exc

        defn = BaseSkillDefinition(
            name=skill_name,
            description=f"Validated skill: {skill_name}",
            skill_path=str(validation.skill_path),
            sig_path=str(validation.sig_path),
            quarantined=True,            # existing: needs 1 success run
            pending_human_approval=True, # FIX #2: needs admin approval first
        )
        self._skills[skill_name] = defn
        self._persist()

        _log.info(
            "R-08/R-09: skill registered (quarantined + pending human approval)",
            extra={
                "skill_name":          skill_name,
                "sig_path":            str(validation.sig_path),
                "pending_approval":    True,
            },
        )
        return defn

    def approve(self, skill_name: str, *, approved_by: str = "admin") -> None:
        """
        FIX #2: Grant human-admin approval for a skill.

        Clears pending_human_approval and records who approved and when.
        After this call, is_executable() will return True (assuming the
        skill is not also quarantined — or the caller passes
        allow_quarantined=True).

        Args:
            skill_name:  Name of the skill to approve.
            approved_by: Identifier of the admin granting approval
                         (e.g. Telegram user_id, "admin_panel", etc.).

        Raises:
            SkillRegistryError: if skill_name is not registered.
        """
        if skill_name not in self._skills:
            raise SkillRegistryError(
                f"Unknown skill {skill_name!r}.",
                skill_name=skill_name,
                reason="UNKNOWN_SKILL",
            )

        defn = self._skills[skill_name]
        if not defn.pending_human_approval:
            _log.info(
                "SkillRegistry: approve() called on already-approved skill (no-op)",
                extra={"skill_name": skill_name},
            )
            return

        defn.pending_human_approval = False
        defn.approved_by = str(approved_by)[:64]
        defn.approved_at = datetime.now(tz=timezone.utc).isoformat()
        self._persist()

        _log.info(
            "FIX-2: skill approved by admin — pending_human_approval cleared",
            extra={
                "skill_name":  skill_name,
                "approved_by": defn.approved_by,
                "approved_at": defn.approved_at,
            },
        )

    def revoke_approval(self, skill_name: str) -> None:
        """
        FIX #2: Revoke a previously granted approval (re-quarantine for review).

        Useful if a skill is found to be misbehaving after approval.

        Raises:
            SkillRegistryError: if skill_name is not registered.
        """
        if skill_name not in self._skills:
            raise SkillRegistryError(
                f"Unknown skill {skill_name!r}.",
                skill_name=skill_name,
                reason="UNKNOWN_SKILL",
            )
        defn = self._skills[skill_name]
        defn.pending_human_approval = True
        defn.approved_by = ""
        defn.approved_at = ""
        defn.quarantined = True          # also re-quarantine
        self._persist()
        _log.warning(
            "FIX-2: skill approval REVOKED — pending_human_approval=True, quarantined=True",
            extra={"skill_name": skill_name},
        )

    def is_executable(self, skill_name: str) -> bool:
        """
        FIX #2: Return True only if the skill is BOTH approved AND not quarantined.

        The agent loop MUST call this before executing any skill.
        Returns False (not True) on unknown skill names.
        """
        defn = self._skills.get(skill_name)
        if defn is None:
            return False
        # Both gates must be clear
        if defn.pending_human_approval:
            return False
        if defn.quarantined:
            return False
        return True

    def get(self, skill_name: str) -> BaseSkillDefinition | None:
        """Return the skill definition for *skill_name*, or None."""
        return self._skills.get(skill_name)

    def list_skills(
        self,
        *,
        include_quarantined: bool = True,
        include_pending: bool = True,
    ) -> list[BaseSkillDefinition]:
        """Return all registered skills with optional filters.

        FIX #2: Added include_pending parameter to filter out skills
        awaiting human approval.

        Bug #11 fix: takes a snapshot copy of _skills before iterating so
        a concurrent register()/remove() from another coroutine cannot
        mutate the dict mid-iteration (raises RuntimeError in Python).
        """
        skills = list(dict(self._skills).values())  # snapshot copy
        if not include_quarantined:
            skills = [s for s in skills if not s.quarantined]
        if not include_pending:
            skills = [s for s in skills if not s.pending_human_approval]
        return sorted(skills, key=lambda s: s.name)

    def list_pending_approval(self) -> list[BaseSkillDefinition]:
        """FIX #2: Return skills waiting for human admin approval."""
        return [s for s in self._skills.values() if s.pending_human_approval]

    def promote(self, skill_name: str) -> None:
        """Lift quarantine on *skill_name* after a successful execution."""
        if skill_name not in self._skills:
            raise SkillRegistryError(
                f"Unknown skill {skill_name!r}.",
                skill_name=skill_name,
                reason="UNKNOWN_SKILL",
            )
        # FIX #2: cannot promote a skill that hasn't been approved yet
        defn = self._skills[skill_name]
        if defn.pending_human_approval:
            raise SkillNotApprovedError(skill_name)

        defn.quarantined = False
        self._persist()
        _log.info(
            "SkillRegistry: skill promoted out of quarantine",
            extra={"skill_name": skill_name},
        )

    def remove(self, skill_name: str) -> bool:
        """Remove *skill_name* from the registry. Returns True if removed."""
        if skill_name in self._skills:
            del self._skills[skill_name]
            self._persist()
            return True
        return False

    def stats(self) -> dict:
        """Return registry statistics for monitoring."""
        skills = list(self._skills.values())
        return {
            "total_skills":    len(skills),
            "active_skills":   sum(1 for s in skills if not s.quarantined and not s.pending_human_approval),
            "quarantined":     sum(1 for s in skills if s.quarantined),
            "pending_approval": sum(1 for s in skills if s.pending_human_approval),
        }

    # ------------------------------------------------------------------
    # Persistence (R-17)
    # ------------------------------------------------------------------

    def _persist(self) -> None:
        """
        Write skill_versions.json atomically and sign immediately (R-17).

        Bug #6 fix: if signing fails after the .json has been written, the
        disk is rolled back to the previous signed state so that a restart
        never encounters an unsigned .json (which would cause the registry
        to load empty and lose all previously registered skills).

        Rollback strategy:
          1. Backup current .json bytes and .sig bytes before writing.
          2. Write new .json via atomic_write_text.
          3. Sign via sign_skill_versions.
          4. If signing fails → restore .json and .sig from backup.
          5. Raise SkillRegistryError so the caller knows the persist failed.
        """
        data = {
            "schema_version": 1,
            "skills": {name: defn.to_dict() for name, defn in self._skills.items()},
        }
        json_text = dumps(data, indent=2)
        sig_path = self._versions_path.with_suffix(".sig")

        # ── Step 1: backup current disk state ─────────────────────────────
        old_json_bytes = safe_read_bytes(self._versions_path)  # None if first write
        old_sig_bytes  = safe_read_bytes(sig_path)             # None if first write

        # ── Step 2: write new .json ───────────────────────────────────────
        atomic_write_text(self._versions_path, json_text, mode=0o644)

        # ── Step 3: sign immediately (R-17) ───────────────────────────────
        try:
            sign_skill_versions(self._versions_path, self._priv_key_path)
        except Exception as exc:
            # ── Step 4: signing failed → ROLLBACK to previous state ───────
            _log.error(
                "R-17: signing failed — rolling back skill_versions.json "
                "to previous signed state",
                extra={
                    "error":          str(exc),
                    "had_backup_json": old_json_bytes is not None,
                    "had_backup_sig":  old_sig_bytes is not None,
                },
            )
            try:
                if old_json_bytes is not None:
                    atomic_write_bytes(
                        self._versions_path, old_json_bytes, mode=0o644,
                    )
                    if old_sig_bytes is not None:
                        atomic_write_bytes(sig_path, old_sig_bytes, mode=0o600)
                else:
                    self._versions_path.unlink(missing_ok=True)
                    sig_path.unlink(missing_ok=True)
            except OSError as rollback_exc:
                _log.error(
                    "R-17: rollback of skill_versions.json ALSO FAILED — "
                    "disk may be in inconsistent state",
                    extra={"rollback_error": str(rollback_exc)},
                )

            raise SkillRegistryError(
                f"Failed to sign skill_versions.json: {exc}. "
                "Disk rolled back to previous signed version (R-17).",
                reason="SIGN_FAILED",
            ) from exc

    def _load_versions(self) -> None:
        """
        Load existing skill_versions.json if present.

        R-17 FIX: The signature is VERIFIED before the file contents are
        parsed.  If the signature is missing, invalid, or the file is
        corrupt, the registry starts empty and logs an error — it does NOT
        load potentially tampered data.
        """
        if not self._versions_path.exists():
            _log.debug("SkillRegistry: no skill_versions.json found — starting empty")
            return

        # R-17: verify signature BEFORE trusting any content
        try:
            verify_skill_versions(self._versions_path, self._pub_key_path)
        except VersionSignatureError as exc:
            _log.error(
                "R-17: skill_versions.json signature invalid — "
                "refusing to load (possible tampering).",
                extra={
                    "path":   str(self._versions_path),
                    "reason": exc.reason,
                },
            )
            return
        except FileNotFoundError:
            _log.warning(
                "R-17: skill_versions.json exists but public key not found — "
                "cannot verify signature, refusing to load.",
                extra={"pub_key": str(self._pub_key_path)},
            )
            return
        except Exception as exc:
            _log.error(
                "R-17: unexpected error verifying skill_versions.json — "
                "refusing to load.",
                extra={"error": str(exc)},
            )
            return

        # Signature verified — safe to parse
        raw = safe_read_bytes(self._versions_path)
        if raw is None:
            return

        try:
            data = loads(raw.decode("utf-8"))
            loaded = 0
            for name, defn_dict in data.get("skills", {}).items():
                self._skills[name] = BaseSkillDefinition.from_dict(defn_dict)
                loaded += 1
            _log.debug(
                "SkillRegistry: loaded skills from verified versions file",
                extra={"loaded": loaded},
            )
        except (JsonDecodeError, UnicodeDecodeError, Exception) as exc:
            _log.warning(
                "SkillRegistry: could not parse skill_versions.json after "
                "signature verification — starting empty.",
                extra={"error": str(exc)},
            )
            self._skills.clear()
