# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
# Copyright (c) 2026 Phidipus Agents (see NOTICE)
"""
skill_validator/skill_signer.py — Phidipus v1.0
ed25519 signing and verification for validated skill files.

Architecture contract (R-09 / R-08 / R-17):
  "SkillLoader MUST verify ed25519 signature (.sig file) before loading any
   skill.  Unsigned skills are rejected with an ERROR log entry."

  "All generated skill code MUST pass skill_validator Gates 1, 2, and 3
   before registration.  No exceptions."

  "R-17 (Phase 1 component): every validated skill .py file MUST be signed
   with ed25519 before registration.  This module fulfils the skill-file
   signing half of R-17.  The second half — signing skill_versions.json
   entries — is implemented in evolution/skill_evolver.py (Phase 4)."

This module is the signing half of the skill integrity pipeline.  It is
called by skill_validator/schema_gate.py immediately after a skill passes
all three gates.  The produced .sig file is the cryptographic proof that
the skill has been validated — SkillLoader refuses to load any .py file
that lacks a valid .sig (R-09).

Signing convention
------------------
For every validated skill file ``<name>.py``, this module writes a sibling
signature file ``<name>.sig`` containing the raw 64-byte ed25519 signature
over the UTF-8 bytes of the .py file.

    skill.py   ← skill source code (written by skill_generator)
    skill.sig  ← 64-byte ed25519 signature (written by this module, mode 0600)

The signature covers the **exact bytes on disk** at the moment of signing.
If the .py file is modified after signing, the .sig becomes invalid and
SkillLoader will reject the skill with a SecurityError.

Key files
---------
Private key (signing):  cfg.skill_validator.signing_private_key_file
                        32-byte raw ed25519 private key, mode 0600
                        Generated by installer via hash_utils.generate_installation_keys()

Public key (verifying): cfg.skill_validator.signing_public_key_file
                        32-byte raw ed25519 public key, mode 0644
                        Consumed by skills/skill_loader.py (R-09)

Process: orchestrator (L1)

Security invariants enforced here:
  R-09  sign_skill() writes a 64-byte ed25519 .sig file alongside the .py.
        verify_skill() raises SkillSignatureError if the .sig is absent,
        has wrong length, or fails cryptographic verification.
  R-17  (Phase 1 component) sign_skill() is the mechanism by which validated
        skill files receive their ed25519 signature.  Every .py file that
        reaches SkillRegistry must have a corresponding .sig produced here.
        The evolution/skill_evolver.py (Phase 4) signs skill_versions.json
        entries — that is the second component of R-17.
  R-07  This module never calls exec(), eval(), exec_module(), or any
        importlib execution primitive.  It reads the skill as raw bytes only.
  R-08  sign_skill() must only be called after all three gates have passed.
        It does not perform Gate checks itself — that is schema_gate.py's
        responsibility.

Used by:
  skill_validator/schema_gate.py  — calls sign_skill() after Gate 3 passes
  (verification only: skills/skill_loader.py has its own _verify_skill_signature
   using hash_utils directly, but callers may also call verify_skill() here)

Dependencies:
  utils/hash_utils.py   — ed25519_sign(), ed25519_verify(),
                          ed25519_load_private_key(), ed25519_load_public_key()
  utils/atomic_file.py  — atomic_write_bytes() for crash-safe .sig write
  utils/file_ops.py     — is_safe_filename() for skill name validation
  utils/logger.py       — get_logger()
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Union

from utils.atomic_file import atomic_write_bytes
from utils.file_ops import is_safe_filename
from utils.hash_utils import (
    ed25519_load_private_key,
    ed25519_load_public_key,
    ed25519_sign,
    ed25519_verify,
)
from utils.logger import get_logger

_log = get_logger(__name__, process="orchestrator")

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

#: Expected length of an ed25519 signature in bytes.
_SIG_LENGTH: int = 64

#: File mode for .sig files: owner read/write only (private by design).
_SIG_FILE_MODE: int = 0o600


# ---------------------------------------------------------------------------
# Exceptions
# ---------------------------------------------------------------------------

class SkillSignatureError(RuntimeError):
    """
    Raised when a skill file's ed25519 signature is absent, malformed, or
    cryptographically invalid.

    This exception is a hard security signal.  A caller that receives it
    MUST NOT load or register the skill.  It should log the event at ERROR
    level and reject the skill permanently.

    Attributes:
        skill_path: Path to the .py skill file involved.
        reason:     Short machine-readable reason code.  One of:
                      SIG_FILE_ABSENT    — .sig sibling file does not exist
                      SIG_WRONG_LENGTH   — .sig file is not exactly 64 bytes
                      INVALID_SIGNATURE  — ed25519 verification returned False
                      CRYPTO_ERROR       — ed25519 library raised an exception
                      UNSAFE_SKILL_NAME  — skill filename failed is_safe_filename()
                      KEY_ERROR          — private or public key file is invalid
    """

    def __init__(
        self,
        message: str,
        *,
        skill_path: Union[str, Path, None] = None,
        reason: str = "VERIFICATION_FAILED",
    ) -> None:
        super().__init__(message)
        self.skill_path = Path(skill_path) if skill_path else None
        self.reason = reason

    def __str__(self) -> str:
        base = super().__str__()
        skill_name = self.skill_path.name if self.skill_path else "<unknown>"
        return f"[{self.reason}] {skill_name}: {base}"


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def sign_skill(
    skill_path: Union[str, Path],
    private_key_path: Union[str, Path],
) -> Path:
    """
    Sign a validated skill file with an ed25519 private key and write the
    64-byte signature to a sibling .sig file (R-09).

    This function MUST be called immediately after a skill passes all three
    validation gates (ast_gate → docker_gate → schema_gate).  The .sig file
    it produces is the only artefact that permits SkillLoader to load the
    skill.

    Signing process:
      1. Validate that skill_path has a safe filename component.
      2. Read the raw bytes of the .py file from disk.
      3. Load the 32-byte raw ed25519 private key from private_key_path.
      4. Compute the 64-byte ed25519 signature over the file bytes.
      5. Write the signature to ``<skill_stem>.sig`` atomically (mode 0600).

    Args:
        skill_path:       Path to the validated .py skill file.  Must already
                          exist and contain the final, committed source.
        private_key_path: Path to the 32-byte raw ed25519 private key file
                          (mode 0600, generated by generate_installation_keys).

    Returns:
        Resolved Path to the .sig file that was written.

    Raises:
        SkillSignatureError: if the skill filename is unsafe (UNSAFE_SKILL_NAME)
                             or the private key is invalid (KEY_ERROR).
        FileNotFoundError:   if skill_path or private_key_path does not exist.
        ImportError:         if the 'cryptography' package is not installed.
        OSError:             on read/write failure.
    """
    skill_path       = Path(skill_path).resolve()
    private_key_path = Path(private_key_path).resolve()

    # ── Validate filename ─────────────────────────────────────────────────
    # is_safe_filename checks the stem without extension; we pass the full
    # name and let it enforce the alphanumeric/underscore/hyphen/dot rule.
    # The .py extension contains a dot which is allowed by is_safe_filename.
    if not is_safe_filename(skill_path.name):
        raise SkillSignatureError(
            f"Skill filename {skill_path.name!r} contains unsafe characters. "
            "Only alphanumerics, underscores, hyphens, and dots are allowed.",
            skill_path=skill_path,
            reason="UNSAFE_SKILL_NAME",
        )

    # ── Check skill file exists ───────────────────────────────────────────
    if not skill_path.exists():
        raise FileNotFoundError(
            f"Skill file not found at {skill_path}. "
            "The skill must be written to disk before signing (R-09)."
        )

    # ── Read skill bytes ──────────────────────────────────────────────────
    skill_bytes = skill_path.read_bytes()

    # ── Load private key and sign ─────────────────────────────────────────
    try:
        private_key = ed25519_load_private_key(private_key_path)
    except (ValueError, OSError) as exc:
        raise SkillSignatureError(
            f"Failed to load ed25519 private key from {private_key_path}: {exc}",
            skill_path=skill_path,
            reason="KEY_ERROR",
        ) from exc

    try:
        signature = ed25519_sign(private_key, skill_bytes)
    except (ValueError, ImportError) as exc:
        raise SkillSignatureError(
            f"ed25519 signing failed for {skill_path.name}: {exc}",
            skill_path=skill_path,
            reason="CRYPTO_ERROR",
        ) from exc

    # ── Write .sig atomically (mode 0600) ─────────────────────────────────
    sig_path = skill_path.with_suffix(".sig")
    atomic_write_bytes(sig_path, signature, mode=_SIG_FILE_MODE)

    _log.debug(
        "R-09: skill signed — .sig file written",
        extra={
            "skill_file":  str(skill_path),
            "sig_file":    str(sig_path),
            "skill_bytes": len(skill_bytes),
            "sig_bytes":   len(signature),
        },
    )
    return sig_path


def verify_skill(
    skill_path: Union[str, Path],
    public_key_path: Union[str, Path],
) -> None:
    """
    Verify that a skill .py file has a valid ed25519 .sig sibling (R-09).

    This function replicates the check performed by SkillLoader internally.
    It is exposed here so callers (e.g. schema_gate.py post-sign assertion,
    integration tests) can verify a skill without going through the full
    loader pipeline.

    Verification process:
      1. Check that the sibling .sig file exists.
      2. Read the raw bytes of the .py file.
      3. Read the 64-byte signature from the .sig file.
      4. Load the 32-byte raw ed25519 public key.
      5. Verify the signature with ed25519_verify().

    Args:
        skill_path:      Path to the .py skill file.
        public_key_path: Path to the 32-byte raw ed25519 public key file.

    Raises:
        SkillSignatureError: if the .sig is absent (SIG_FILE_ABSENT), has
                             wrong length (SIG_WRONG_LENGTH), fails
                             cryptographic verification (INVALID_SIGNATURE),
                             or the library raises (CRYPTO_ERROR).
        FileNotFoundError:   if skill_path does not exist.
        ImportError:         if the 'cryptography' package is not installed.
        OSError:             on read failure.
    """
    skill_path      = Path(skill_path).resolve()
    public_key_path = Path(public_key_path).resolve()
    sig_path        = skill_path.with_suffix(".sig")

    if not skill_path.exists():
        raise FileNotFoundError(
            f"Skill file not found at {skill_path}."
        )

    # ── Check .sig file exists ────────────────────────────────────────────
    if not sig_path.exists():
        _log.error(
            "R-09 VIOLATION: skill .sig file absent",
            extra={
                "skill_file": str(skill_path),
                "sig_file":   str(sig_path),
            },
        )
        raise SkillSignatureError(
            f"Signature file {sig_path.name} is absent. "
            "The skill must pass all three validation gates and be signed "
            "before it can be verified or loaded (R-09).",
            skill_path=skill_path,
            reason="SIG_FILE_ABSENT",
        )

    # ── Read skill bytes and signature ────────────────────────────────────
    skill_bytes = skill_path.read_bytes()
    signature   = sig_path.read_bytes()

    if len(signature) != _SIG_LENGTH:
        _log.error(
            "R-09 VIOLATION: skill .sig has wrong length",
            extra={
                "skill_file":      str(skill_path),
                "sig_file":        str(sig_path),
                "sig_length":      len(signature),
                "expected_length": _SIG_LENGTH,
            },
        )
        raise SkillSignatureError(
            f"Signature file {sig_path.name} has unexpected length "
            f"{len(signature)} bytes (expected {_SIG_LENGTH}). "
            "The .sig file may be corrupt or was not written by sign_skill() (R-09).",
            skill_path=skill_path,
            reason="SIG_WRONG_LENGTH",
        )

    # ── Load public key and verify ────────────────────────────────────────
    try:
        public_key = ed25519_load_public_key(public_key_path)
    except (ValueError, OSError) as exc:
        raise SkillSignatureError(
            f"Failed to load ed25519 public key from {public_key_path}: {exc}",
            skill_path=skill_path,
            reason="KEY_ERROR",
        ) from exc

    try:
        valid = ed25519_verify(public_key, skill_bytes, signature)
    except (ValueError, ImportError) as exc:
        _log.error(
            "R-09: ed25519 verification raised an exception",
            extra={
                "skill_file": str(skill_path),
                "error":      str(exc),
            },
        )
        raise SkillSignatureError(
            f"ed25519 verification error for {skill_path.name}: {exc}",
            skill_path=skill_path,
            reason="CRYPTO_ERROR",
        ) from exc

    if not valid:
        _log.error(
            "R-09 VIOLATION: skill signature INVALID",
            extra={
                "skill_file": str(skill_path),
                "sig_file":   str(sig_path),
                "reason":     "INVALID_SIGNATURE",
            },
        )
        raise SkillSignatureError(
            f"Skill {skill_path.name!r} signature is invalid. "
            "The .py file may have been modified after signing, or the "
            "signing key has changed.  Re-run skill validation to produce "
            "a new signed skill (R-09).",
            skill_path=skill_path,
            reason="INVALID_SIGNATURE",
        )

    _log.debug(
        "R-09: skill signature verified OK",
        extra={
            "skill_file": str(skill_path),
            "sig_file":   str(sig_path),
        },
    )


def sig_path_for(skill_path: Union[str, Path]) -> Path:
    """
    Return the expected .sig path for a given skill .py path.

    This is a pure path computation — it does not check whether the file
    exists.  Callers that need existence checks should use ``verify_skill()``
    or check ``sig_path_for(skill_path).exists()`` directly.

    Args:
        skill_path: Path to the .py skill file.

    Returns:
        Path to the expected sibling .sig file (same directory, same stem).

    Example::

        sig = sig_path_for("/data/skills/open_browser.py")
        # → Path("/data/skills/open_browser.sig")
    """
    return Path(skill_path).with_suffix(".sig")


def is_skill_signed(
    skill_path: Union[str, Path],
    public_key_path: Union[str, Path],
) -> bool:
    """
    Return True if the skill at *skill_path* has a valid .sig file.

    A convenience wrapper around ``verify_skill()`` that absorbs
    ``SkillSignatureError`` and returns False instead.  Useful for
    listing or filtering skills without raising on each invalid entry.

    Never raises (absorbs all exceptions).  If you need to know *why*
    verification failed, call ``verify_skill()`` directly.

    Args:
        skill_path:      Path to the .py skill file.
        public_key_path: Path to the ed25519 public key file.

    Returns:
        True if the skill exists and has a valid signature, False otherwise.
    """
    try:
        verify_skill(skill_path, public_key_path)
        return True
    except (SkillSignatureError, FileNotFoundError, ImportError, OSError) as exc:
        _log.debug(
            "is_skill_signed: verification failed",
            extra={
                "skill_file": str(skill_path),
                "reason":     type(exc).__name__,
                "error":      str(exc),
            },
        )
        return False
