# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
# Copyright (c) 2026 Phidipus Agents (see NOTICE)
"""
evolution/skill_version_signer.py — Phidipus v1.0.2
Signing and verification helpers for skill_versions.json.

Architecture contract (R-17):
  "Every entry in skill_versions.json MUST be signed with ed25519.
   SkillEvolver MUST NOT write an unsigned version entry."

This module provides two public functions:

  sign_skill_versions()   — call after every write to skill_versions.json.
  verify_skill_versions() — call before reading skill_versions.json.

Design:
  - The signature covers the raw bytes of skill_versions.json as written to
    disk.  This means the file must be fully written and fsynced before
    sign_skill_versions() is called, and the bytes read by verify must match
    those bytes exactly.
  - The .sig file is written with mode 0600 (owner read/write only).
  - Both functions are stateless; the private/public key paths are passed by
    the caller and loaded from disk on each call.  No key material is cached
    in module state.
  - SkillEvolver must call sign_skill_versions() immediately after every
    atomic write to skill_versions.json.  The write + sign sequence should
    be treated as a single logical operation.

Usage (in SkillEvolver.write_version_entry):

    from utils.atomic_file import atomic_write_text
    from evolution.skill_version_signer import sign_skill_versions

    # Step 1: write the updated versions file atomically.
    atomic_write_text(versions_path, json_text)

    # Step 2: sign immediately — before any other process can read the file.
    sign_skill_versions(versions_path, private_key_path)

Usage (in SkillLoader or startup integrity check):

    from evolution.skill_version_signer import verify_skill_versions

    verify_skill_versions(versions_path, public_key_path)
    # Raises SecurityError if signature is missing or invalid.

Dependencies:
  utils/hash_utils.py — ed25519_sign(), ed25519_verify(),
                         ed25519_load_private_key(), ed25519_load_public_key()
  utils/logger.py     — structured JSON logging
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Union

from utils.hash_utils import (
    ed25519_load_private_key,
    ed25519_load_public_key,
    ed25519_sign,
    ed25519_verify,
)
from utils.logger import get_logger

_log = get_logger("evolution.skill_version_signer", process="orchestrator")


# ---------------------------------------------------------------------------
# Exceptions
# ---------------------------------------------------------------------------

class VersionSignatureError(RuntimeError):
    """
    Raised when skill_versions.json signature verification fails.

    Attributes:
        versions_path: Path to the skill_versions.json file.
        reason:        Short machine-readable reason code.
    """

    def __init__(
        self,
        message: str,
        *,
        versions_path: Union[str, Path, None] = None,
        reason: str = "VERIFICATION_FAILED",
    ) -> None:
        super().__init__(message)
        self.versions_path = Path(versions_path) if versions_path else None
        self.reason = reason

    def __str__(self) -> str:
        base = super().__str__()
        if self.versions_path:
            return f"[{self.reason}] {self.versions_path.name}: {base}"
        return f"[{self.reason}] {base}"


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def sign_skill_versions(
    versions_path: Union[str, Path],
    private_key_path: Union[str, Path],
) -> Path:
    """
    Sign *versions_path* (skill_versions.json) with an ed25519 private key
    and write the 64-byte signature to a sibling .sig file.

    This function must be called immediately after every write to
    skill_versions.json (R-17).  The .sig file is written with mode 0600.

    Signing process:
      1. Read the raw bytes of skill_versions.json from disk.
      2. Load the 32-byte raw ed25519 private key from *private_key_path*.
      3. Compute the 64-byte ed25519 signature over the file bytes.
      4. Write the signature to ``skill_versions.sig`` (same directory).

    Args:
        versions_path:    Path to skill_versions.json.  Must already exist
                          and contain the final, committed content.
        private_key_path: Path to the 32-byte raw ed25519 private key file
                          (mode 0600, generated by generate_installation_keys).

    Returns:
        Resolved Path to the .sig file that was written.

    Raises:
        FileNotFoundError: if versions_path or private_key_path does not exist.
        ValueError:        if the private key file is not exactly 32 bytes.
        ImportError:       if the 'cryptography' package is not installed.
        OSError:           on read/write failure.
    """
    versions_path    = Path(versions_path).resolve()
    private_key_path = Path(private_key_path).resolve()

    if not versions_path.exists():
        raise FileNotFoundError(
            f"skill_versions.json not found at {versions_path}. "
            "The file must be written before signing (R-17)."
        )

    # ── Read file bytes ───────────────────────────────────────────────────
    data = versions_path.read_bytes()

    # ── Load private key and sign ─────────────────────────────────────────
    private_key = ed25519_load_private_key(private_key_path)
    signature   = ed25519_sign(private_key, data)

    # ── Write signature file (mode 0600) ──────────────────────────────────
    sig_path = versions_path.with_suffix(".sig")
    sig_path.write_bytes(signature)
    os.chmod(sig_path, 0o600)

    _log.debug(
        "R-17: skill_versions.json signed",
        extra={
            "versions_file": str(versions_path),
            "sig_file":      str(sig_path),
            "sig_bytes":     len(signature),
        },
    )
    return sig_path


def verify_skill_versions(
    versions_path: Union[str, Path],
    public_key_path: Union[str, Path],
) -> None:
    """
    Verify that skill_versions.json has a valid ed25519 signature.

    This function should be called before reading skill_versions.json at
    startup or before any SkillEvolver operation that reads version history.

    Verification process:
      1. Check that ``skill_versions.sig`` exists alongside the .json file.
      2. Read the raw bytes of skill_versions.json.
      3. Read the 64-byte signature from skill_versions.sig.
      4. Verify the signature with ed25519_verify().

    Args:
        versions_path:   Path to skill_versions.json.
        public_key_path: Path to the 32-byte raw ed25519 public key file.

    Raises:
        VersionSignatureError: if the .sig file is absent, has wrong length,
                               or the signature is cryptographically invalid.
        FileNotFoundError:     if versions_path does not exist.
        ValueError:            if the public key file is not exactly 32 bytes.
        ImportError:           if the 'cryptography' package is not installed.
        OSError:               on read failure.
    """
    versions_path   = Path(versions_path).resolve()
    public_key_path = Path(public_key_path).resolve()
    sig_path        = versions_path.with_suffix(".sig")

    if not versions_path.exists():
        raise FileNotFoundError(
            f"skill_versions.json not found at {versions_path}."
        )

    # ── Check .sig file exists ────────────────────────────────────────────
    if not sig_path.exists():
        _log.error(
            "R-17 VIOLATION: skill_versions.sig absent",
            extra={
                "versions_file": str(versions_path),
                "sig_file":      str(sig_path),
            },
        )
        raise VersionSignatureError(
            f"Signature file {sig_path.name} is absent. "
            "skill_versions.json must always have a valid .sig file (R-17).",
            versions_path=versions_path,
            reason="SIG_FILE_ABSENT",
        )

    # ── Read bytes and signature ──────────────────────────────────────────
    data      = versions_path.read_bytes()
    signature = sig_path.read_bytes()

    if len(signature) != 64:
        _log.error(
            "R-17 VIOLATION: skill_versions.sig has wrong length",
            extra={
                "sig_file":       str(sig_path),
                "sig_length":     len(signature),
                "expected_length": 64,
            },
        )
        raise VersionSignatureError(
            f"Signature file {sig_path.name} has unexpected length "
            f"{len(signature)} bytes (expected 64). "
            "The .sig file may be corrupt (R-17).",
            versions_path=versions_path,
            reason="SIG_WRONG_LENGTH",
        )

    # ── Cryptographic verification ────────────────────────────────────────
    public_key = ed25519_load_public_key(public_key_path)

    try:
        valid = ed25519_verify(public_key, data, signature)
    except (ValueError, ImportError) as exc:
        _log.error(
            "R-17: ed25519 verification raised an exception",
            extra={
                "versions_file": str(versions_path),
                "error":         str(exc),
            },
        )
        raise VersionSignatureError(
            f"ed25519 verification error for skill_versions.json: {exc}",
            versions_path=versions_path,
            reason="CRYPTO_ERROR",
        ) from exc

    if not valid:
        _log.error(
            "R-17 VIOLATION: skill_versions.json signature INVALID",
            extra={
                "versions_file": str(versions_path),
                "reason":        "INVALID_SIGNATURE",
            },
        )
        raise VersionSignatureError(
            "skill_versions.json signature is invalid. "
            "The file may have been tampered with or the signing key has "
            "changed.  Re-run installation to regenerate keys and re-sign "
            "all skill version entries (R-17).",
            versions_path=versions_path,
            reason="INVALID_SIGNATURE",
        )

    _log.debug(
        "R-17: skill_versions.json signature verified OK",
        extra={"versions_file": str(versions_path)},
    )
